function mp_gantt4latex(X, t, range, fileName)
   %   Gantt chart generation from X to LaTeX source
   %
   %   MP_GANTT4LATEX(X, t, range, fileName)
   %   - X state or output vector (matrix),
   %   - t time vector - vector with time operations
   %   - range - max range to which Gantt has been draw, default: 50
   %   - fileName (optional) a file for source latex code, default: mp_gantt.tex
   %
   %   See also
   %   MP_MX2LATEX, MP_TAB4LATEX
   %
   %   Introduced in ver.1.8
   %
   %   Max-Plus Algebra Toolbox for Matlab, ver.1.8, 2023-March-06
   %   Copyright (C) 2003-2023 Jaroslaw Stanczyk, <jaroslaw.stanczyk@upwr.edu.pl>

   _header1_ = "\
%%\n\
%% mp_gantt.tex\n\
%% Copyright (C) 2003-2023 Jaroslaw Stanczyk, <jaroslaw.stanczyk@upwr.edu.pl>\n\
%% automatically generated by mpa v1.8 on ";

   _header2_ = "\
\n\
%%\n\
\\documentclass{standalone}\n\
\n\
\\usepackage{pgfgantt}\n\
\n\
\\begin{document}\n\
\n\
\\newganttchartelement{barmyA}{\n\
	barmyA/.style={\n\
		inner sep=0pt,\n\
		draw=red!50,\n\
		very thick,\n\
		top color=white,\n\
		bottom color=red!50,\n\
		fill opacity=0.5,\n\
		pattern=north west lines\n\
	},\n\
	barmyA height=0.7\n\
}\n\
\n\
\\newganttchartelement{barmyB}{\n\
	barmyB/.style={\n\
		inner sep=0pt,\n\
		draw=blue!50,\n\
		very thick,\n\
		top color=white,\n\
		bottom color=blue!50,\n\
		fill opacity=0.5,\n\
		pattern=north west lines\n\
	},\n\
	barmyB height=0.7\n\
}\n\
\n\
\\newganttchartelement{barmyC}{\n\
	barmyC/.style={\n\
		inner sep=0pt,\n\
		draw=green!50,\n\
		very thick,\n\
		top color=white,\n\
		bottom color=green!50,\n\
		fill opacity=0.5,\n\
		pattern=north west lines\n\
	},\n\
	barmyC height=0.7\n\
}\n\
\n\
\\newganttchartelement{barmyD}{\n\
	barmyD/.style={\n\
		inner sep=0pt,\n\
		draw=yellow!50,\n\
		very thick,\n\
		top color=white,\n\
		bottom color=yellow!50,\n\
		fill opacity=0.5,\n\
		pattern=north west lines\n\
	},\n\
	barmyD height=0.7\n\
}\n\
\n\
\\begin{ganttchart}[\n\
	vgrid,\n\
	y unit chart=0.5cm,\n\
	bar height=0.7,\n\
	bar/.append style={fill=gray!50},\n\
]";

   _footer_ = "\
\\end{ganttchart}\n\
\\end{document}";

   narginchk(2, 4);
   switch nargin
      case 2
         range = 50;
         fileName = 'mp_gantt.tex';
      case 3
         fileName = 'mp_gantt.tex';
   end

   if (isempty(X) || isempty(t))
      error('mp_gantt2latex: an empty input parameter')
   end

   SizeX = size(X);
   SizeT = size(t);
   if (SizeX(1, 1) ~= SizeT(1, 2))
      error('mp_gantt4latex: inconsistent X and t size');
   end

   fid = fopen(fileName, 'w+');
   fprintf(fid, _header1_);
   fprintf(fid, strftime("%A %e %B %Y, %R:%S %Z", localtime(time())));
   fprintf(fid, _header2_);
   fprintf(fid, '{0}{%d}\n', range);
   fprintf(fid, '\\gantttitlelist{0,...,%d}{1}\\\\\n', range);

   for i = 1:SizeX(1, 1)
      for j = 1:SizeX(1, 2)
         if (j == 1)
            fprintf(fid, '\\ganttbarmyA{$x_{%d}$}{%d}{%d}\n', i, X(i, j), X(i, j)+t(i)-1);
         else
            k = mod(j, 4);
            if (k == 0)
               fprintf(fid, '\\ganttbarmyB{}{%d}{%d}\n', X(i, j), X(i, j)+t(i)-1);
            elseif (k == 1)
               fprintf(fid, '\\ganttbarmyA{}{%d}{%d}\n', X(i, j), X(i, j)+t(i)-1);
            elseif (k == 2)
               fprintf(fid, '\\ganttbarmyC{}{%d}{%d}\n', X(i, j), X(i, j)+t(i)-1);
            elseif (k == 3)
               fprintf(fid, '\\ganttbarmyD{}{%d}{%d}\n', X(i, j), X(i, j)+t(i)-1);
            end
         end
      end
      fprintf(fid, '\\\\\n');
   end

   fprintf(fid, _footer_);
   fclose(fid);
end

% end of file
